/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VisMain {
        "data": any;
    }
    interface VisMainSidebar {
    }
}
declare global {
    interface HTMLVisMainElement extends Components.VisMain, HTMLStencilElement {
    }
    var HTMLVisMainElement: {
        prototype: HTMLVisMainElement;
        new (): HTMLVisMainElement;
    };
    interface HTMLVisMainSidebarElement extends Components.VisMainSidebar, HTMLStencilElement {
    }
    var HTMLVisMainSidebarElement: {
        prototype: HTMLVisMainSidebarElement;
        new (): HTMLVisMainSidebarElement;
    };
    interface HTMLElementTagNameMap {
        "vis-main": HTMLVisMainElement;
        "vis-main-sidebar": HTMLVisMainSidebarElement;
    }
}
declare namespace LocalJSX {
    interface VisMain {
        "data"?: any;
    }
    interface VisMainSidebar {
    }
    interface IntrinsicElements {
        "vis-main": VisMain;
        "vis-main-sidebar": VisMainSidebar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vis-main": LocalJSX.VisMain & JSXBase.HTMLAttributes<HTMLVisMainElement>;
            "vis-main-sidebar": LocalJSX.VisMainSidebar & JSXBase.HTMLAttributes<HTMLVisMainSidebarElement>;
        }
    }
}
