/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LegendData, MainData, SidebarChartData, SidebarData, SidebarMetadataData, SidebarSelection, TimeControlData } from "./utils/data";
export namespace Components {
    interface VisMain {
        "data": MainData;
        "serverFileAPIPath": string;
    }
    interface VisMainLegend {
        "data": LegendData;
    }
    interface VisMainLongbar {
        "data": SidebarData;
    }
    interface VisMainSidebar {
        "data": SidebarData;
        "pins": SidebarSelection[];
    }
    interface VisMainSidebarBarChart {
        "data": SidebarChartData;
    }
    interface VisMainSidebarLineChart {
        "data": SidebarChartData;
    }
    interface VisMainSidebarMetadata {
        "data": SidebarMetadataData;
    }
    interface VisMainTimeControl {
        "data": TimeControlData;
    }
}
declare global {
    interface HTMLVisMainElement extends Components.VisMain, HTMLStencilElement {
    }
    var HTMLVisMainElement: {
        prototype: HTMLVisMainElement;
        new (): HTMLVisMainElement;
    };
    interface HTMLVisMainLegendElement extends Components.VisMainLegend, HTMLStencilElement {
    }
    var HTMLVisMainLegendElement: {
        prototype: HTMLVisMainLegendElement;
        new (): HTMLVisMainLegendElement;
    };
    interface HTMLVisMainLongbarElement extends Components.VisMainLongbar, HTMLStencilElement {
    }
    var HTMLVisMainLongbarElement: {
        prototype: HTMLVisMainLongbarElement;
        new (): HTMLVisMainLongbarElement;
    };
    interface HTMLVisMainSidebarElement extends Components.VisMainSidebar, HTMLStencilElement {
    }
    var HTMLVisMainSidebarElement: {
        prototype: HTMLVisMainSidebarElement;
        new (): HTMLVisMainSidebarElement;
    };
    interface HTMLVisMainSidebarBarChartElement extends Components.VisMainSidebarBarChart, HTMLStencilElement {
    }
    var HTMLVisMainSidebarBarChartElement: {
        prototype: HTMLVisMainSidebarBarChartElement;
        new (): HTMLVisMainSidebarBarChartElement;
    };
    interface HTMLVisMainSidebarLineChartElement extends Components.VisMainSidebarLineChart, HTMLStencilElement {
    }
    var HTMLVisMainSidebarLineChartElement: {
        prototype: HTMLVisMainSidebarLineChartElement;
        new (): HTMLVisMainSidebarLineChartElement;
    };
    interface HTMLVisMainSidebarMetadataElement extends Components.VisMainSidebarMetadata, HTMLStencilElement {
    }
    var HTMLVisMainSidebarMetadataElement: {
        prototype: HTMLVisMainSidebarMetadataElement;
        new (): HTMLVisMainSidebarMetadataElement;
    };
    interface HTMLVisMainTimeControlElement extends Components.VisMainTimeControl, HTMLStencilElement {
    }
    var HTMLVisMainTimeControlElement: {
        prototype: HTMLVisMainTimeControlElement;
        new (): HTMLVisMainTimeControlElement;
    };
    interface HTMLElementTagNameMap {
        "vis-main": HTMLVisMainElement;
        "vis-main-legend": HTMLVisMainLegendElement;
        "vis-main-longbar": HTMLVisMainLongbarElement;
        "vis-main-sidebar": HTMLVisMainSidebarElement;
        "vis-main-sidebar-bar-chart": HTMLVisMainSidebarBarChartElement;
        "vis-main-sidebar-line-chart": HTMLVisMainSidebarLineChartElement;
        "vis-main-sidebar-metadata": HTMLVisMainSidebarMetadataElement;
        "vis-main-time-control": HTMLVisMainTimeControlElement;
    }
}
declare namespace LocalJSX {
    interface VisMain {
        "data"?: MainData;
        "serverFileAPIPath"?: string;
    }
    interface VisMainLegend {
        "data"?: LegendData;
    }
    interface VisMainLongbar {
        "data"?: SidebarData;
    }
    interface VisMainSidebar {
        "data"?: SidebarData;
        "pins"?: SidebarSelection[];
    }
    interface VisMainSidebarBarChart {
        "data"?: SidebarChartData;
    }
    interface VisMainSidebarLineChart {
        "data"?: SidebarChartData;
    }
    interface VisMainSidebarMetadata {
        "data"?: SidebarMetadataData;
    }
    interface VisMainTimeControl {
        "data"?: TimeControlData;
    }
    interface IntrinsicElements {
        "vis-main": VisMain;
        "vis-main-legend": VisMainLegend;
        "vis-main-longbar": VisMainLongbar;
        "vis-main-sidebar": VisMainSidebar;
        "vis-main-sidebar-bar-chart": VisMainSidebarBarChart;
        "vis-main-sidebar-line-chart": VisMainSidebarLineChart;
        "vis-main-sidebar-metadata": VisMainSidebarMetadata;
        "vis-main-time-control": VisMainTimeControl;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vis-main": LocalJSX.VisMain & JSXBase.HTMLAttributes<HTMLVisMainElement>;
            "vis-main-legend": LocalJSX.VisMainLegend & JSXBase.HTMLAttributes<HTMLVisMainLegendElement>;
            "vis-main-longbar": LocalJSX.VisMainLongbar & JSXBase.HTMLAttributes<HTMLVisMainLongbarElement>;
            "vis-main-sidebar": LocalJSX.VisMainSidebar & JSXBase.HTMLAttributes<HTMLVisMainSidebarElement>;
            "vis-main-sidebar-bar-chart": LocalJSX.VisMainSidebarBarChart & JSXBase.HTMLAttributes<HTMLVisMainSidebarBarChartElement>;
            "vis-main-sidebar-line-chart": LocalJSX.VisMainSidebarLineChart & JSXBase.HTMLAttributes<HTMLVisMainSidebarLineChartElement>;
            "vis-main-sidebar-metadata": LocalJSX.VisMainSidebarMetadata & JSXBase.HTMLAttributes<HTMLVisMainSidebarMetadataElement>;
            "vis-main-time-control": LocalJSX.VisMainTimeControl & JSXBase.HTMLAttributes<HTMLVisMainTimeControlElement>;
        }
    }
}
